name=input("რა გქვია: ")
surname=input("რა არის შენი გვარი: ")
age=input("რამდენი წლის ხარ: ")
family_members=input("რამდენი ოჯახის წევრი გყავს: ")
favourite_food=input("რა არის შენი საყვარელი საჭმელი: ")
math_point=input("რა არის შენი მათემატიკის წლიური ქულა: ")
favourite_actor=input("ვინაა შენი საყვარელი მსახიობი: ")
favourite_film=input("რომელია შენი საყვარელი ფილმი: ")
favourite_singer=input("ვინაა შენი საყვარელი მომღერალი: ")
favourite_song=input("რომელია შენი საყვარელი სიმღერა: ") 
print("მან თქვა რომ მისი სახელია " + name + ","  + "მისი გვარია " + surname + "," + "ის არის "  + str(age) + "წლის" + "," + "მის ოჯახში ცხოვრობს " + str(family_members) + "წევრი " + "." + "მან თქვა რომ მისი საყვარელი საჭმელია " + favourite_food + "," + "მისი მათემატიკის წლიური ნიშანია " + math_point + "," +  "მისი საყვარელი მსხიობია" + favourite_actor + "," + "მისი საყვარელი ფილმია" + favourite_film + "." +"მან თქვა რომ მისი საყვარელი მომღერალია " + favourite_singer + "," +  "მისი საყვარელი სიმღერაა " + favourite_song + "." )